args <- commandArgs(trailingOnly = TRUE)
lesson_path <- if (length(args)) args[[1]] else file.path("examples", "lesson")
root <- normalizePath(".", winslash = "/", mustWork = TRUE)
source(file.path(root, "R", "utils.R"))
source(file.path(root, "R", "zzz.R"))
source(file.path(root, "R", "lesson_manifest.R"))
source(file.path(root, "R", "check_lesson.R"))
report <- check_lesson(lesson_path)
print(report, row.names = FALSE)
if (any(report$status == "FAIL")) quit(status = 1)
