root <- normalizePath(".", winslash = "/", mustWork = TRUE)
source(file.path(root, "R", "utils.R"))
source(file.path(root, "R", "zzz.R"))
source(file.path(root, "R", "lesson_bundle.R"))
source(file.path(root, "R", "scene_contract.R"))
source(file.path(root, "R", "lesson_manifest.R"))
source(file.path(root, "R", "render_scene.R"))
source(file.path(root, "R", "scaffold_lesson.R"))
source(file.path(root, "R", "check_lesson.R"))

tmp <- tempfile("rlearnxr-smoke-")
scaffold_lesson(tmp, title = "Smoke Lesson")
stopifnot(file.exists(file.path(tmp, "index.qmd")))
demo <- data.frame(x = c(-1, 0, 1), y = c(0, 1, 0), z = c(1, 0, -1))
render_scene(demo, "x", "y", "z", output_dir = file.path(tmp, "scene"))
stopifnot(file.exists(file.path(tmp, "scene", "index.html")))
html <- paste(readLines(file.path(tmp, "scene", "index.html"), warn = FALSE), collapse = "\n")
stopifnot(grepl('id="prediction-input"', html, fixed = TRUE))
stopifnot(grepl('id="r-code-editor"', html, fixed = TRUE))
stopifnot(grepl('id="run-r-code"', html, fixed = TRUE))
stopifnot(grepl('webr.r-wasm.org', html, fixed = TRUE))
stopifnot(grepl('id="check-sync"', html, fixed = TRUE))
stopifnot(grepl('id="points-table"', html, fixed = TRUE))
stopifnot(grepl('id="download-receipt"', html, fixed = TRUE))
stopifnot(grepl('private_data_sent_to_ai: false', html, fixed = TRUE))
stopifnot(grepl('tabindex="0"', html, fixed = TRUE))
writeLines("Generated smoke-test data under CC0.", file.path(tmp, "DATA_LICENSE.md"))
results <- check_lesson(tmp)
stopifnot(!any(results$status == "FAIL"))
strict_results <- check_lesson(tmp, write_report = FALSE, strict = TRUE)
stopifnot(any(strict_results$status == "FAIL" & strict_results$check == "data_license"))
stopifnot(file.exists(file.path(tmp, "checks", "reproducibility-report.json")))
cat("R-LearnXR smoke test passed.\n")
