root <- normalizePath(".", winslash = "/", mustWork = TRUE)
source(file.path(root, "R", "utils.R"))
source(file.path(root, "R", "zzz.R"))
source(file.path(root, "R", "render_scene.R"))
source(file.path(root, "R", "scaffold_lesson.R"))
source(file.path(root, "R", "check_lesson.R"))

tmp <- tempfile("rlearnxr-smoke-")
scaffold_lesson(tmp, title = "Smoke Lesson")
stopifnot(file.exists(file.path(tmp, "index.qmd")))
demo <- data.frame(x = c(-1, 0, 1), y = c(0, 1, 0), z = c(1, 0, -1))
render_scene(demo, "x", "y", "z", output_dir = file.path(tmp, "scene"))
stopifnot(file.exists(file.path(tmp, "scene", "index.html")))
html <- paste(readLines(file.path(tmp, "scene", "index.html"), warn = FALSE), collapse = "\n")
stopifnot(grepl('id="prediction-input"', html, fixed = TRUE))
stopifnot(grepl('id="points-table"', html, fixed = TRUE))
stopifnot(grepl('tabindex="0"', html, fixed = TRUE))
writeLines("Generated smoke-test data under CC0.", file.path(tmp, "DATA_LICENSE.md"))
results <- check_lesson(tmp)
stopifnot(!any(results$status == "FAIL" & results$check != "environment_lock"))
cat("R-LearnXR smoke test passed.\n")
