scaffold_lesson <- function(path = "rclaimlab-lesson", title = "R-ClaimLab Lesson", overwrite = FALSE) {
  path <- normalizePath(path, winslash = "/", mustWork = FALSE)
  if (dir.exists(path) && !overwrite && length(list.files(path, all.files = TRUE, no.. = TRUE)) > 0) {
    stop("path already contains files; use overwrite = TRUE to replace the scaffold", call. = FALSE)
  }
  ensure_dir(path)
  ensure_dir(file.path(path, "data"))
  ensure_dir(file.path(path, "scene"))
  ensure_dir(file.path(path, "checks"))

  quarto_yml <- paste0(
    "project:\n",
    "  type: website\n",
    "  output-dir: _site\n",
    "execute:\n",
    "  freeze: auto\n",
    "  execute-dir: project\n",
    "format:\n",
    "  html:\n",
    "    toc: true\n"
  )
  index_qmd <- paste0(
    "---\n",
    "title: \"", title, "\"\n",
    "format: html\n",
    "---\n\n",
    "# Learning objectives\n\n",
    "By the end, learners can state a data prediction, run a reproducible R transformation, explain one coordinate as evidence, and transfer the reasoning to a new point.\n\n",
    "## Predict, explore, explain, transfer\n\n",
    "Predict before running R. Explore the scene or semantic table. Explain one point with a coordinate and a limitation. Transfer the reasoning to a second point, then reproduce the result from the exported source.\n\n",
    "This lesson is generated by **R-ClaimLab**. The browser laboratory includes an editable WebR exercise, an optional 3D evidence view, release checks, and export to ordinary R and Quarto source.\n\n",
    "```{r}\n",
    "#| echo: true\n",
    "library(rclaimlab)\n",
    "set.seed(2026)\n",
    "demo <- data.frame(\n",
    "  x = c(-0.9, -0.4, 0.1, 0.5, 0.9),\n",
    "  y = c(0.6, -0.2, 0.5, -0.7, 0.1),\n",
    "  z = c(-0.4, 0.4, 0.8, -0.1, 0.5),\n",
    "  label = c('clean', 'join', 'model', 'diagnose', 'share')\n",
    ")\n",
    "render_scene(demo, 'x', 'y', 'z', labels = demo$label, output_dir = 'scene', title = 'Lesson data space', overwrite = TRUE)\n",
    "```\n\n",
    "[Open the interactive R and 3D laboratory](scene/index.html)\n"
  )
  readme <- paste0(
    "# ", title, "\n\n",
    "This lesson was scaffolded by R-ClaimLab.\n\n",
    "## Reproduce\n\n",
    "1. Install R and Quarto.\n2. Run `renv::restore()` from this directory. The scaffold includes a minimal `renv.lock`; run `renv::snapshot()` after installing the packages used by the lesson.\n3. Run `quarto render`.\n4. Run `rclaimlab::check_lesson(strict = TRUE)` and inspect both reports under `checks/`.\n"
  )
  data_license <- paste0(
    "# Data License and Provenance\n\n",
    "Replace this starter note before publishing. Record the dataset source, license, transformations, and any ethical or privacy limits.\n"
  )
  r_version <- paste(R.version$major, R.version$minor, sep = ".")
  renv_lock <- paste0(
    "{\n",
    "  \"R\": {\n",
    "    \"Version\": \"", r_version, "\",\n",
    "    \"Repositories\": [{\"Name\": \"CRAN\", \"URL\": \"https://cloud.r-project.org\"}]\n",
    "  },\n",
    "  \"Packages\": {}\n",
    "}\n"
  )
  writeLines(quarto_yml, file.path(path, "_quarto.yml"), useBytes = TRUE)
  writeLines(index_qmd, file.path(path, "index.qmd"), useBytes = TRUE)
  writeLines(readme, file.path(path, "README.md"), useBytes = TRUE)
  writeLines(data_license, file.path(path, "DATA_LICENSE.md"), useBytes = TRUE)
  writeLines(renv_lock, file.path(path, "renv.lock"), useBytes = TRUE)
  writeLines(c("_site/", "_freeze/", "renv/library/", ".Rhistory"), file.path(path, ".gitignore"), useBytes = TRUE)
  write_lesson_manifest(
    path = path, lesson_id = basename(path), title = title,
    source_platform = "rclaimlab", source_project = "rclaimlab",
    dataset_file = "data/source.csv", dataset_source = "",
    dataset_license = "", overwrite = TRUE
  )
  invisible(path)
}
