scaffold_lesson <- function(path = "rlearnxr-lesson", title = "R-LearnXR Lesson", overwrite = FALSE) {
  path <- normalizePath(path, winslash = "/", mustWork = FALSE)
  if (dir.exists(path) && !overwrite && length(list.files(path, all.files = TRUE, no.. = TRUE)) > 0) {
    stop("path already contains files; use overwrite = TRUE to replace the scaffold", call. = FALSE)
  }
  ensure_dir(path)
  ensure_dir(file.path(path, "data"))
  ensure_dir(file.path(path, "scene"))
  ensure_dir(file.path(path, "checks"))

  quarto_yml <- paste0(
    "project:\n",
    "  type: website\n",
    "  output-dir: _site\n",
    "execute:\n",
    "  freeze: auto\n",
    "  execute-dir: project\n",
    "format:\n",
    "  html:\n",
    "    toc: true\n"
  )
  index_qmd <- paste0(
    "---\n",
    "title: \"", title, "\"\n",
    "format: html\n",
    "---\n\n",
    "This lesson is generated by **R-LearnXR**. The 3D scene is an optional browser-based view; the analysis remains reproducible as ordinary R and Quarto code.\n\n",
    "```{r}\n",
    "#| echo: true\n",
    "library(rlearnxr)\n",
    "set.seed(2026)\n",
    "demo <- data.frame(\n",
    "  x = c(-0.9, -0.4, 0.1, 0.5, 0.9),\n",
    "  y = c(0.6, -0.2, 0.5, -0.7, 0.1),\n",
    "  z = c(-0.4, 0.4, 0.8, -0.1, 0.5),\n",
    "  label = c('clean', 'join', 'model', 'diagnose', 'share')\n",
    ")\n",
    "render_scene(demo, 'x', 'y', 'z', labels = demo$label, output_dir = 'scene', title = 'Lesson data space')\n",
    "```\n\n",
    "[Open the interactive 3D scene](scene/index.html)\n"
  )
  readme <- paste0(
    "# ", title, "\n\n",
    "This lesson was scaffolded by R-LearnXR.\n\n",
    "## Reproduce\n\n",
    "1. Install R and Quarto.\n2. Restore the project environment with `renv::restore()` after creating `renv.lock`.\n3. Run `quarto render`.\n4. Run `rlearnxr::check_lesson()` and inspect `checks/reproducibility-report.md`.\n"
  )
  data_license <- paste0(
    "# Data License and Provenance\n\n",
    "Replace this text with the dataset source, license, transformations, and any ethical or privacy limits before publishing the lesson.\n"
  )
  writeLines(quarto_yml, file.path(path, "_quarto.yml"), useBytes = TRUE)
  writeLines(index_qmd, file.path(path, "index.qmd"), useBytes = TRUE)
  writeLines(readme, file.path(path, "README.md"), useBytes = TRUE)
  writeLines(data_license, file.path(path, "DATA_LICENSE.md"), useBytes = TRUE)
  writeLines(c("_site/", "_freeze/", "renv/library/", ".Rhistory"), file.path(path, ".gitignore"), useBytes = TRUE)
  invisible(path)
}
